[12/07/2018 20:20] ERROR owner load 74: extension does not have a setup function
Traceback (most recent call last):
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\owner.py", line 65, in load
    self._load_cog(module)
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\owner.py", line 948, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "lib\discord\ext\commands\bot.py", line 736, in load_extension
    raise discord.ClientException('extension does not have a setup function')
discord.errors.ClientException: extension does not have a setup function
[12/07/2018 20:21] ERROR owner load 74: No module named 'cogs.utils.menu'
Traceback (most recent call last):
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\owner.py", line 65, in load
    self._load_cog(module)
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\owner.py", line 946, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "D:\Programs\Python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\desutils.py", line 4, in <module>
    from .utils.menu import *
ModuleNotFoundError: No module named 'cogs.utils.menu'
[12/07/2018 20:23] ERROR red load_cogs 573: No module named 'cogs.utils.menu'
Traceback (most recent call last):
  File "red.py", line 570, in load_cogs
    owner_cog._load_cog(extension)
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\owner.py", line 946, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "D:\Programs\Python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\desutils.py", line 4, in <module>
    from .utils.menu import *
ModuleNotFoundError: No module named 'cogs.utils.menu'
[12/07/2018 20:23] ERROR red load_cogs 573: You don't have Pillow installed, run
```pip3 install pillow```And try again
Traceback (most recent call last):
  File "red.py", line 570, in load_cogs
    owner_cog._load_cog(extension)
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\owner.py", line 948, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "lib\discord\ext\commands\bot.py", line 738, in load_extension
    lib.setup(self)
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\identicon.py", line 298, in setup
    raise RuntimeError("You don't have Pillow installed, run\n```pip3 install pillow```And try again")
RuntimeError: You don't have Pillow installed, run
```pip3 install pillow```And try again
[12/07/2018 20:23] ERROR red load_cogs 573: extension does not have a setup function
Traceback (most recent call last):
  File "red.py", line 570, in load_cogs
    owner_cog._load_cog(extension)
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\owner.py", line 948, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "lib\discord\ext\commands\bot.py", line 736, in load_extension
    raise discord.ClientException('extension does not have a setup function')
discord.errors.ClientException: extension does not have a setup function
[12/07/2018 21:35] ERROR red load_cogs 573: You need to run `pip3 install pillow`
Traceback (most recent call last):
  File "red.py", line 570, in load_cogs
    owner_cog._load_cog(extension)
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\owner.py", line 948, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "lib\discord\ext\commands\bot.py", line 738, in load_extension
    lib.setup(self)
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\spoiler.py", line 111, in setup
    raise RuntimeError("You need to run `pip3 install pillow`")
RuntimeError: You need to run `pip3 install pillow`
[12/07/2018 21:45] ERROR owner load 74: No module named 'cogs.utils.menu'
Traceback (most recent call last):
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\owner.py", line 65, in load
    self._load_cog(module)
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\owner.py", line 946, in _load_cog
    mod_obj = importlib.import_module(cogname)
  File "D:\Programs\Python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\desutils.py", line 4, in <module>
    from .utils.menu import *
ModuleNotFoundError: No module named 'cogs.utils.menu'
[12/07/2018 21:48] ERROR owner load 74: You don't have Pillow installed, run
```pip3 install pillow```And try again
Traceback (most recent call last):
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\owner.py", line 65, in load
    self._load_cog(module)
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\owner.py", line 948, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "lib\discord\ext\commands\bot.py", line 738, in load_extension
    lib.setup(self)
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\identicon.py", line 298, in setup
    raise RuntimeError("You don't have Pillow installed, run\n```pip3 install pillow```And try again")
RuntimeError: You don't have Pillow installed, run
```pip3 install pillow```And try again
[12/07/2018 21:48] ERROR owner load 74: You need to run `pip3 install pillow`
Traceback (most recent call last):
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\owner.py", line 65, in load
    self._load_cog(module)
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\owner.py", line 948, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "lib\discord\ext\commands\bot.py", line 738, in load_extension
    lib.setup(self)
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\spoiler.py", line 111, in setup
    raise RuntimeError("You need to run `pip3 install pillow`")
RuntimeError: You need to run `pip3 install pillow`
[12/07/2018 22:58] ERROR red on_command_error 369: Exception in command 'welcomeset'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\welcome.py", line 34, in welcomeset
    self.settings[server.id]["CHANNEL"] = server.default_channel.id
AttributeError: 'NoneType' object has no attribute 'id'
[13/07/2018 00:32] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "lib\aiohttp\connector.py", line 601, in _create_direct_connection
    local_addr=self._local_addr)
  File "D:\Programs\Python\lib\asyncio\base_events.py", line 802, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "D:\Programs\Python\lib\asyncio\base_events.py", line 828, in _create_connection_transport
    yield from waiter
  File "D:\Programs\Python\lib\asyncio\selector_events.py", line 724, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib\aiohttp\connector.py", line 304, in connect
    yield from self._create_connection(req)
  File "lib\aiohttp\connector.py", line 578, in _create_connection
    transport, proto = yield from self._create_direct_connection(req)
  File "lib\aiohttp\connector.py", line 624, in _create_direct_connection
    (req.host, req.port, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 10054] Can not connect to discordapp.com:443 [An existing connection was forcibly closed by the remote host]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "D:\Programs\Python\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
  File "lib\discord\client.py", line 416, in login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "lib\discord\client.py", line 346, in _login_1
    data = yield from self.http.static_login(token, bot=is_bot)
  File "lib\discord\http.py", line 258, in static_login
    data = yield from self.request(Route('GET', '/users/@me'))
  File "lib\discord\http.py", line 137, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "lib\aiohttp\client.py", line 555, in __iter__
    resp = yield from self._coro
  File "lib\aiohttp\client.py", line 198, in _request
    conn = yield from self._connector.connect(req)
  File "lib\aiohttp\connector.py", line 314, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 10054] Cannot connect to host discordapp.com:443 ssl:True [Can not connect to discordapp.com:443 [An existing connection was forcibly closed by the remote host]]
[13/07/2018 01:00] ERROR red on_command_error 369: Exception in command 'welcomeset'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\welcome.py", line 34, in welcomeset
    self.settings[server.id]["CHANNEL"] = server.default_channel.id
AttributeError: 'NoneType' object has no attribute 'id'
[13/07/2018 01:12] ERROR red on_command_error 369: Exception in command 'adminset selfroles'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\admin.py", line 132, in adminset_selfroles
    parsed_role_set = list({r.name for r in parsed_roles})
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\admin.py", line 132, in <setcomp>
    parsed_role_set = list({r.name for r in parsed_roles})
AttributeError: 'NoneType' object has no attribute 'name'
[13/07/2018 01:24] ERROR red on_command_error 369: Exception in command 'rss force'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "D:\Programs\Discord Bot\Red-DiscordBot\cogs\rss.py", line 211, in _rss_force
    await self.bot.say(message)
  File "lib\discord\ext\commands\bot.py", line 309, in _augmented_msg
    msg = yield from coro
  File "red.py", line 92, in send_message
    return await super().send_message(*args, **kwargs)
  File "lib\discord\client.py", line 1151, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "lib\discord\http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400): Cannot send an empty message
